### ISSUE TITLE
[Question about --max_disp in triaining]

### ISSUE THREAD

**Issue by CaptainEven** [LongguangWang/PAM#11]
what 's the difference between set max_disp to 192 and set to 0?

**Comment by LongguangWang** [comment]
Hi @CaptainEven, thanks for your interest in our work. When max_disp is set to 192, our PAM only finds correspondence in stereo images within disparity range [0, 192]. When max_disp is set to 0, the disparity range to find correspondence will be extended to [0, ∞].

**Comment by CaptainEven** [comment]
@LongguangWang Thank you for your detailed explanation! I got it.
