### ISSUE TITLE
为什么无监督立体匹配却在计算损失的时候关联了很多真实的视差值？

### ISSUE THREAD

**Issue by Zhang-zhimin** [LongguangWang/PAM#6]
作者您好，很感谢你的工作和代码分享，我想请教一下，论文是无监督立体匹配，为什么在代码的损失计算中，mask_left，mask_right是用真实视差值计算出来的，用在了损失的计算中，非常不解，谢谢您的回复

**Comment by LongguangWang** [comment]
@Zhang-zhimin 你好，感谢对我们工作的关注。一般双目匹配网络在SceneFlow上进行训练的时候，只计算disp<192区域内的loss。为了跟他们保持一致，我们使用了mask_left和mask_right来保证损失函数只在disp<192区域内进行计算。这两个mask对我们的网络不是必要的，把它们去掉后也可以正常训练。

**Comment by Zhang-zhimin** [comment]
谢谢您的回复，解答了我的疑惑，感谢！！！
