### ISSUE TITLE
[performance comparison] Is PAM performing better than MonoDepthV2?

### ISSUE THREAD

**Issue by CaptainEven** [LongguangWang/PAM#8]
Thank you for your excellent work! Do you provide performance comparisons with some other unsupervised(or self-supervised) depth estimation like MonoDepthV2?

**Comment by LongguangWang** [comment]
Hi @CaptainEven, thanks for your interest in our work. Since we focus on unsupervised stereo matching in this work, we do not include unsupervised monocular depth estimation into comparison.

**Comment by CaptainEven** [comment]
@LongguangWang  Got it! Thanks for the explanation. I will do a comparison latter, and give a feedback as soon as possible.
